[tool.poetry]
name = "bigdata-fecaf"
version = "0.1.0"
description = "Projeto de Big Data com Streamlit e PostgreSQL"
authors = ["Seu Nome <seu@email.com>"]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "*"
pandas = "*"
sqlalchemy = "*"
psycopg2-binary = "*"
plotly = "*"
python-dotenv = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
